import React,{useEffect,useRef,useState} from 'react';
import {Alert,Animated,Image,Linking,Pressable,ScrollView,Text,View} from 'react-native';
import {RecordingPresets,requestRecordingPermissionsAsync,setAudioModeAsync,useAudioPlayer,useAudioPlayerStatus,useAudioRecorder,useAudioRecorderState} from 'expo-audio';
import {Body,Button,Card,H1,H2} from '../components/Ui';
import rawLesson from '../data/botLesson.json';
import {lessonImages,suitcaseImages} from '../data/lessonImages';
import {ANIMAL_PAIR_OPTIONS,CARD_OPTIONS,GIFT_OPTIONS,GIRAFFE_CHOICES,LOCALIZED_IMAGE_MASKS,MOOD_EMOJIS,SUITCASE_ITEMS,VOICE_EXAMPLES_RU,adaptivePrompt,buildRuntimeOrder,selectedCardBranch,type NormalizedRect,type SelectableImageOption} from '../data/lessonInteractions';
import {API_BASE,completeSession,isUnauthorizedError,saveSessionProgress,sendInteractive,sendVoice,startSession,translateText,ttsSource} from '../api/mobile';
import {useAppStore} from '../store/AppStore';

const lesson:any=rawLesson;
const allSlides:any[]=lesson.slides||[];
const runtimeOrder=buildRuntimeOrder(allSlides);

function mediaSource(slide:any){const name=String(slide?.image||'').split('/').pop();return name&&lessonImages[name]?lessonImages[name]:undefined}
function isConfiguredVoice(slide:any){return ['required_voice','optional_voice'].includes(slide?.answer_mode)}
function rectStyle(rect:NormalizedRect){return {left:`${rect.left*100}%`,top:`${rect.top*100}%`,width:`${rect.width*100}%`,height:`${rect.height*100}%`} as any}

function SelectableArtwork({slide,source,targetLanguage,heroUri,heroAnim,options,selected,onSelect}:{slide:any;source:any;targetLanguage:string;heroUri?:string;heroAnim:Animated.Value;options:SelectableImageOption[];selected:string;onSelect:(value:string)=>void}){
  const name=String(slide.image||'').split('/').pop()||'';const masks:NormalizedRect[]=targetLanguage==='ru'?[]:(LOCALIZED_IMAGE_MASKS[name]||[]);
  return <View style={{position:'relative',width:'100%',aspectRatio:16/9,borderRadius:18,overflow:'hidden',backgroundColor:'#fff',marginBottom:12}}>
    <Image source={source} style={{position:'absolute',width:'100%',height:'100%',resizeMode:'contain'}}/>
    {masks.map((rect,index)=><View key={`mask-${index}`} pointerEvents='none' style={[{position:'absolute',backgroundColor:'rgba(255,255,255,0.97)',borderRadius:8},rectStyle(rect)]}/>) }
    {options.map(option=><Pressable key={option.id} testID={`lesson-target-${slide.slide_id}-${option.id}`} accessibilityRole='button' accessibilityLabel={option.label} onPress={()=>onSelect(option.id)} style={[{position:'absolute',borderRadius:12,borderWidth:selected===option.id?5:2,borderColor:selected===option.id?'#13a864':'rgba(255,255,255,0.72)',backgroundColor:selected===option.id?'rgba(19,168,100,0.16)':'transparent'},rectStyle(option.rect)]}><Text style={{position:'absolute',right:4,bottom:3,backgroundColor:'#fff',borderRadius:11,paddingHorizontal:6,fontWeight:'900'}}>{selected===option.id?'✓':' '}</Text></Pressable>)}
    {heroUri?<View pointerEvents='none' style={{position:'absolute',right:8,bottom:4,width:105,height:145}}><Animated.Image source={{uri:heroUri}} style={{width:105,height:145,resizeMode:'contain',transform:[{translateY:heroAnim.interpolate({inputRange:[0,1],outputRange:[0,-4]})}]}}/></View>:null}
  </View>;
}

export function LessonPlayer(){
  const store=useAppStore();const child=store.selectedChild;
  const[session,setSession]=useState<number>();const[idx,setIdx]=useState(0);const[attempt,setAttempt]=useState(1);const[recording,setRecording]=useState(false);const[busy,setBusy]=useState(false);const[accepted,setAccepted]=useState(false);const[feedback,setFeedback]=useState('');const[choice,setChoice]=useState('');const[packed,setPacked]=useState<string[]>([]);const[completed,setCompleted]=useState<any>();const[targetText,setTargetText]=useState('');const[nativeText,setNativeText]=useState('');const[voiceLoading,setVoiceLoading]=useState(false);const[interactiveState,setInteractiveState]=useState<Record<string,any>>({});const[recordedPhrases,setRecordedPhrases]=useState<string[]>([]);const[riddleRevealed,setRiddleRevealed]=useState(false);
  const recorder=useAudioRecorder(RecordingPresets.HIGH_QUALITY);const recorderState=useAudioRecorderState(recorder,200);const voicePlayer=useAudioPlayer(null);const voiceStatus=useAudioPlayerStatus(voicePlayer);const heroAnim=useRef(new Animated.Value(0)).current;const stoppingRef=useRef(false);const slide=runtimeOrder[idx];
  const targetLang=child?.learningLanguage||'ru';const nativeLang=child?.nativeLanguage||'ru';const audioBusy=voiceLoading||voiceStatus.playing||voiceStatus.isBuffering;
  const isSelector=slide?.type==='card_selector';const isSuitcase=slide?.interactive_task==='suitcase';const isAnimalPair=slide?.type==='animal_compare';const isMood=slide?.type==='mood_choice';const isGift=slide?.slide_id==='slide_20';const isGiraffe=slide?.slide_id==='slide_45';
  const voiceKey=String(slide?.required_phrase_id||slide?.slide_id||'');const needsVoice=isConfiguredVoice(slide)||isAnimalPair||isSelector;const canRecord=needsVoice&&(!isSelector||Boolean(choice))&&(!isAnimalPair||Boolean(choice))&&(!isGift||Boolean(choice))&&(!isSuitcase||packed.length>0)&&(!isGiraffe||riddleRevealed);
  const heroUri=child?.heroUrl?(child.heroUrl.startsWith('http')?child.heroUrl:API_BASE+child.heroUrl):undefined;

  useEffect(()=>{let active=true;(async()=>{if(!child)return;try{const response=await startSession(child.id,'demo_001');if(!active)return;setInteractiveState(response.interactive_state||{});setRecordedPhrases(response.recorded_phrases||[]);setSession(response.session_id);setAttempt(response.run_number||1);setIdx(Math.min(Math.max(Number(response.current_step)||0,0),Math.max(runtimeOrder.length-1,0)))}catch(error:any){if(!active||isUnauthorizedError(error))return;Alert.alert('Урок недоступен',error.message);store.setScreen('home')}})();return()=>{active=false}},[child?.id]);

  useEffect(()=>{if(!slide||!session)return;let dead=false;const stored=interactiveState[slide.slide_id]||{};const restoredChoice=String(stored.choice||stored.selected_animal||stored.selected_gift||stored.mood||'');const restoredPacked=Array.isArray(stored.selected)?stored.selected.map(String):[];const hasVoice=recordedPhrases.includes(String(slide.required_phrase_id||slide.slide_id));setChoice(restoredChoice);setPacked(restoredPacked);setRiddleRevealed(Boolean(stored.revealed));setFeedback('');setAccepted(isMood?Boolean(restoredChoice):isSuitcase?hasVoice&&restoredPacked.length>0:(isAnimalPair||isSelector||isGift)?hasVoice&&Boolean(restoredChoice):needsVoice?hasVoice:true);Animated.loop(Animated.sequence([Animated.timing(heroAnim,{toValue:1,duration:800,useNativeDriver:true}),Animated.timing(heroAnim,{toValue:0,duration:800,useNativeDriver:true})]),{iterations:2}).start();(async()=>{try{const baseTarget=adaptivePrompt(slide,child?.languageLevel);const baseNative=slide.bot_explains_native||'';const[translatedTarget,translatedNative]=await Promise.all([translateText(baseTarget,targetLang,'ru'),translateText(baseNative,nativeLang,'ru')]);if(dead)return;setTargetText(translatedTarget||baseTarget);setNativeText(translatedNative||baseNative);await speakTarget(translatedTarget||baseTarget,targetLang)}catch(error){console.warn('slide voice/translation error',error)}})();return()=>{dead=true}},[idx,session,targetLang,nativeLang,child?.languageLevel]);
  useEffect(()=>{const limit=Math.max(1,Number(slide?.max_voice_seconds||5))*1000;if(recording&&recorderState.durationMillis>=limit&&!stoppingRef.current)void stopRec()},[recording,recorderState.durationMillis,slide?.slide_id]);

  async function speakTarget(text:string,sourceLanguage=targetLang){if(!text)return;try{setVoiceLoading(true);voicePlayer.replace(await ttsSource(text,targetLang,'',nativeLang,sourceLanguage));voicePlayer.play()}catch(error:any){console.warn('AI TTS error',error);setFeedback('Голос ведущей временно недоступен.')}finally{setVoiceLoading(false)}}
  async function persistInteraction(result:any){if(!session||!slide)return;setInteractiveState(current=>({...current,[slide.slide_id]:result}));await sendInteractive(session,slide.slide_id,slide.interactive_task||slide.type||'choice',result)}

  async function chooseArtwork(value:string){
    if(busy)return;setChoice(value);setAccepted(false);
    try{
      if(isSelector){const branch=selectedCardBranch(allSlides,value);await persistInteraction({choice:value,branch_slide_id:branch?.slide_id});const base=adaptivePrompt(branch||slide,child?.languageLevel);const[translated,native]=await Promise.all([translateText(base,targetLang,'ru'),translateText(branch?.bot_explains_native||'',nativeLang,'ru')]);setTargetText(translated||base);setNativeText(native||'');setFeedback('Карточка выбрана. Теперь ответь голосом.');await speakTarget(translated||base,targetLang);return}
      if(isAnimalPair){await persistInteraction({selected_animal:value,pair_id:slide.pair_id});const example=await translateText(VOICE_EXAMPLES_RU[voiceKey]||'Я вижу животное.',targetLang,'ru');setTargetText(example);setFeedback('Животное выбрано. Послушай пример ведущей и ответь голосом.');await speakTarget(example,targetLang);return}
      if(isGift){await persistInteraction({selected_gift:value});const selected=GIFT_OPTIONS.find(item=>item.id===value);const example=await translateText(`Мила подарила мне ${selected?.label||'подарок'}.`,targetLang,'ru');setTargetText(example);setFeedback('Подарок выбран. Послушай пример ведущей и назови подарок голосом.');await speakTarget(example,targetLang);return}
    }catch(error:any){setFeedback('Не удалось сохранить выбор: '+error.message)}
  }

  async function chooseGiraffe(value:string){if(value!=='giraffe'){setFeedback('Послушай загадку ещё раз и попробуй другой рисунок.');await speakTarget(targetText,targetLang);return}setChoice(value);setRiddleRevealed(true);setAccepted(recordedPhrases.includes('giraffe'));await persistInteraction({choice:value,revealed:true});const example=await translateText('Это жираф. У него длинная шея и пятна.',targetLang,'ru');setFeedback('Верно! Послушай пример и назови один-два признака.');await speakTarget(example,targetLang)}
  async function toggleSuitcase(itemId:string){const selected=packed.includes(itemId)?packed.filter(id=>id!==itemId):[...packed,itemId];setPacked(selected);setAccepted(false);try{await persistInteraction({selected,useful_selected:selected.filter(id=>SUITCASE_ITEMS.some(item=>item.id===id&&item.useful)),completed:selected.length>0})}catch(error:any){setFeedback('Не удалось сохранить чемодан: '+error.message)}}
  async function chooseMood(index:number){const mood=String(slide.mood_options?.[index]||`mood_${index}`);setChoice(mood);setAccepted(true);await persistInteraction({mood,index,emoji:MOOD_EMOJIS[index]});const spoken=await translateText(mood,targetLang,'ru');setTargetText(spoken);setFeedback('Настроение выбрано ✓');await speakTarget(spoken,targetLang)}

  async function startRec(){if(!session||busy||recording||audioBusy||!canRecord)return;try{stoppingRef.current=false;const permission=await requestRecordingPermissionsAsync();if(!permission.granted){Alert.alert('Нужен доступ к микрофону');return}await setAudioModeAsync({allowsRecording:true,playsInSilentMode:true});await recorder.prepareToRecordAsync();recorder.record();setRecording(true);setAccepted(false);setFeedback('Говори — я тебя слушаю. Когда закончишь, нажми ещё раз.')}catch(error:any){Alert.alert('Микрофон',error.message)}}
  async function stopRec(){if(!recording||!session||busy||stoppingRef.current)return;stoppingRef.current=true;try{setBusy(true);setFeedback('Слушаю и проверяю ответ…');await recorder.stop();setRecording(false);const uri=recorder.uri;if(!uri)throw new Error('Файл записи не создан');const response=await sendVoice(session,uri,slide.slide_id,slide.required_phrase_id,targetText||slide.question||slide.bot_says_target||'');const serverAccepted=Boolean(response.accepted)||String(response.status||'').startsWith('ACCEPTED');if(serverAccepted)setRecordedPhrases(items=>items.includes(voiceKey)?items:[...items,voiceKey]);setAccepted(serverAccepted);const heard=response.transcript?`Я услышала: «${response.transcript}». `:'';setFeedback(heard+(response.feedback||response.response_native||(serverAccepted?'Отлично! Можно идти дальше.':'Послушай правильный вариант и повтори.')));const correction=String(response.correction_target||'');if(correction)await speakTarget(correction,targetLang);else if(response.response_target)await speakTarget(String(response.response_target),targetLang)}catch(error:any){console.error('stopRec error',error);setRecording(false);setAccepted(false);setFeedback('Запись не засчитана: '+error.message)}finally{try{await setAudioModeAsync({allowsRecording:false,playsInSilentMode:true})}catch{}stoppingRef.current=false;setBusy(false)}}

  const next=async()=>{if(!accepted||busy||audioBusy)return;if(idx<runtimeOrder.length-1){try{setBusy(true);if(session)await saveSessionProgress(session,idx+1);setIdx(value=>value+1)}catch(error:any){Alert.alert('Не удалось сохранить урок',error.message)}finally{setBusy(false)}return}if(!session)return;try{setBusy(true);setCompleted(await completeSession(session))}catch(error:any){Alert.alert('Не удалось завершить урок',error.message)}finally{setBusy(false)}};
  const exitLesson=async()=>{try{if(session)await saveSessionProgress(session,idx)}catch(error:any){Alert.alert('Не удалось сохранить урок',error.message);return}store.setScreen('home')};

  if(completed)return <ScrollView contentContainerStyle={{padding:24}}><H1>Урок завершён 🎉</H1><Card><H2>Прохождение {completed.run_number||attempt} из 2</H2>{completed.movie_status==='READY'?<Body>🎬 Персональный мультфильм M‑1 готов.</Body>:<Body muted>🎬 Мультфильм: {completed.movie_status==='PROCESSING'?'обрабатывается на сервере':completed.movie_status==='MISSING_VOICE'?'нужны все реплики урока':'пока недоступен'}.</Body>}{completed.movie_url?<Button title='▶ Посмотреть мультфильм' onPress={()=>Linking.openURL(completed.movie_url)}/>:null}</Card><Button title='Вернуться домой' onPress={()=>store.setScreen('home')}/></ScrollView>;
  if(!slide)return <View style={{padding:24}}><Body>Загрузка урока…</Body></View>;

  const source=mediaSource(slide);let artworkOptions:SelectableImageOption[]=[];if(isSelector)artworkOptions=CARD_OPTIONS;else if(isGift)artworkOptions=GIFT_OPTIONS;else if(isAnimalPair)artworkOptions=ANIMAL_PAIR_OPTIONS[slide.pair_id]||[];const showArtwork=Boolean(source)&&!isSuitcase&&!isMood&&(!isGiraffe||riddleRevealed);

  return <ScrollView contentContainerStyle={{padding:18,paddingBottom:42}} keyboardShouldPersistTaps='handled'><H1>DOME · {targetLang.toUpperCase()}</H1><Body muted>{idx+1}/{runtimeOrder.length} · прохождение {attempt}/2 · уровень {child?.languageLevel||'PRE_A1'}</Body>
    {showArtwork?<SelectableArtwork slide={slide} source={source} targetLanguage={targetLang} heroUri={heroUri} heroAnim={heroAnim} options={artworkOptions} selected={choice} onSelect={chooseArtwork}/>:null}
    {isGiraffe&&!riddleRevealed?<Card><H2>Угадай по голосу</H2><View style={{flexDirection:'row',justifyContent:'space-around'}}>{GIRAFFE_CHOICES.map(item=><Pressable testID={`giraffe-choice-${item.id}`} accessibilityRole='button' accessibilityLabel={item.label} key={item.id} onPress={()=>chooseGiraffe(item.id)} style={{minWidth:82,minHeight:82,borderRadius:18,borderWidth:3,borderColor:choice===item.id?'#13a864':'#d9dee6',alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:50}}>{item.emoji}</Text></Pressable>)}</View></Card>:null}
    {isSuitcase?<Card><H2>🧳 Чемодан</H2><Body>Нажми на вещь, чтобы положить её в чемодан. Нажми ещё раз, чтобы вынуть.</Body><View testID='suitcase-drop-zone' style={{minHeight:105,borderWidth:3,borderStyle:'dashed',borderColor:'#6aa6d8',borderRadius:18,padding:8,flexDirection:'row',flexWrap:'wrap',gap:6}}>{packed.length?packed.map(id=><Pressable key={`packed-${id}`} onPress={()=>toggleSuitcase(id)}><Image source={suitcaseImages[id]} style={{width:66,height:66,resizeMode:'contain'}}/></Pressable>):<Body muted>Здесь появятся выбранные вещи</Body>}</View><View style={{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:10}}>{SUITCASE_ITEMS.filter(item=>!packed.includes(item.id)).map(item=><Pressable testID={`suitcase-item-${item.id}`} accessibilityRole='button' accessibilityLabel={item.label} key={item.id} onPress={()=>toggleSuitcase(item.id)} style={{width:'22%',minHeight:82,borderWidth:1,borderColor:'#ddd',borderRadius:12,alignItems:'center',justifyContent:'center'}}><Image source={suitcaseImages[item.id]} style={{width:62,height:62,resizeMode:'contain'}}/></Pressable>)}</View></Card>:null}
    {isMood?<Card><H2>Какое у тебя настроение?</H2><View style={{flexDirection:'row',flexWrap:'wrap',gap:10,justifyContent:'center'}}>{MOOD_EMOJIS.map((emoji,index)=><Pressable testID={`mood-${index}`} accessibilityRole='button' accessibilityLabel={`Mood ${index+1}`} key={index} onPress={()=>chooseMood(index)} style={{width:88,height:88,borderRadius:22,borderWidth:4,borderColor:choice===slide.mood_options?.[index]?'#13a864':'#d9dee6',alignItems:'center',justifyContent:'center',backgroundColor:'#fff'}}><Text style={{fontSize:54}}>{emoji}</Text></Pressable>)}</View></Card>:null}
    <Card>{targetText?<><Body muted>Ведущая говорит ({targetLang})</Body><H2>{targetText}</H2></>:null}{nativeText&&nativeLang!==targetLang?<><Body muted>Подсказка для родителя ({nativeLang})</Body><Body>{nativeText}</Body></>:null}<Button secondary disabled={audioBusy||recording} title={audioBusy?'🔊 Ведущая говорит…':'🔊 Повторить голос ведущей'} onPress={()=>speakTarget(targetText,targetLang)}/>{canRecord?<><Button testID='record-answer' disabled={busy||audioBusy} title={audioBusy?'🔊 Дослушай ведущую…':recording?'⏹ Закончить запись':'🎙 Записать ответ'} onPress={recording?stopRec:startRec}/><Body muted>После исправления ведущая произнесёт правильный вариант голосом и попросит повторить. Не больше трёх попыток.</Body></>:null}{feedback?<Body>{feedback}</Body>:null}</Card>
    <Button disabled={!accepted||busy||audioBusy} title={idx<runtimeOrder.length-1?'Дальше →':'Завершить урок'} onPress={next}/><Button secondary title='🌍 Изменить языки' onPress={()=>store.setScreen('language')}/><Button secondary title='Выйти и сохранить место' onPress={exitLesson}/>
  </ScrollView>;
}
