import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Alert,Animated,Image,Linking,Pressable,ScrollView,Text,useWindowDimensions,Vibration,View} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {RecordingPresets,requestRecordingPermissionsAsync,setAudioModeAsync,useAudioPlayer,useAudioPlayerStatus,useAudioRecorder,useAudioRecorderState} from 'expo-audio';
import {Body,Button,Card,H1,H2} from '../components/Ui';
import bundledLesson from '../data/botLesson.json';
import {lessonImages,suitcaseImages} from '../data/lessonImages';
import {ANIMAL_PAIR_OPTIONS,CARD_OPTIONS,GIRAFFE_CHOICES,MOOD_EMOJIS,SUITCASE_ITEMS,VOICE_EXAMPLES_RU,buildRuntimeOrder,selectedCardBranch,type NormalizedRect,type SelectableImageOption} from '../data/lessonInteractions';
import {API_BASE,completeSession,getLesson,isUnauthorizedError,lessonVisualSource,saveSessionProgress,sendInteractive,sendVoice,startSession,translateText,ttsSource} from '../api/mobile';
import {advanceAfterAssessment,cardQuestions,cardVoiceKey,heroBox,lessonLayoutPolicy,nextCardQuestion,nextEnabled,recordEnabled,requiresSelection,requiresVoice,runtimePrompt,stageAfterTutorSpeech,type RuntimeStage} from '../engine/lessonRuntime';
import {useAppStore} from '../store/AppStore';

function mediaSource(slide:any){const name=String(slide?.image||'').split('/').pop();return name&&lessonImages[name]?lessonImages[name]:undefined}
function configuredOptions(slide:any,fallback:SelectableImageOption[]=[]):SelectableImageOption[]{
  if(!Array.isArray(slide?.selection_options))return fallback;
  return slide.selection_options.map((item:any)=>({id:String(item.id),label:String(item.label||item.id),emoji:item.emoji?String(item.emoji):undefined,rect:{left:Number(item.rect?.[0]||0),top:Number(item.rect?.[1]||0),width:Number(item.rect?.[2]||0),height:Number(item.rect?.[3]||0)}}));
}
function selectedAnswerValueRu(slide:any,value:string):string{return String(slide?.selection_options?.find?.((item:any)=>String(item.id)===value)?.answer_value_ru||'подарок')}
function rectStyle(rect:NormalizedRect|number[]){
  const values=Array.isArray(rect)?{left:rect[0]||0,top:rect[1]||0,width:rect[2]||0,height:rect[3]||0}:rect;
  return {left:`${values.left*100}%`,top:`${values.top*100}%`,width:`${values.width*100}%`,height:`${values.height*100}%`} as any;
}

function SelectableArtwork({slide,source,heroUri,heroRect,heroAnim,options,selected,onSelect,onImageError}:{slide:any;source:any;heroUri?:string;heroRect:number[]|null;heroAnim:Animated.Value;options:SelectableImageOption[];selected:string;onSelect:(value:string)=>void;onImageError:()=>void}){
  return <View style={{position:'relative',width:'100%',aspectRatio:16/9,borderRadius:18,overflow:'hidden',backgroundColor:'#fff',marginBottom:10}}>
    <Image source={source} onError={onImageError} style={{position:'absolute',width:'100%',height:'100%',resizeMode:'contain'}}/>
    {options.map(option=><Pressable key={option.id} testID={`lesson-target-${slide.slide_id}-${option.id}`} accessibilityRole='button' accessibilityLabel={option.label} onPress={()=>onSelect(option.id)} style={[{position:'absolute',borderRadius:12,borderWidth:selected===option.id?5:(selected?0:2),borderColor:selected===option.id?'#13a864':'rgba(255,255,255,0.8)',backgroundColor:selected===option.id?'rgba(19,168,100,0.18)':'transparent',transform:[{scale:selected===option.id?1.06:1}]},rectStyle(option.rect)]}>{selected===option.id?<Text style={{position:'absolute',right:4,bottom:3,backgroundColor:'#fff',borderRadius:11,paddingHorizontal:6,fontWeight:'900'}}>✓</Text>:null}</Pressable>)}
    {heroUri&&heroRect?<View pointerEvents='none' style={[{position:'absolute'},rectStyle(heroRect)]}><Animated.Image source={{uri:heroUri}} style={{width:'100%',height:'100%',resizeMode:'contain',transform:[{translateY:heroAnim.interpolate({inputRange:[0,1],outputRange:[0,-4]})}]}}/></View>:null}
  </View>;
}

export function LessonPlayer(){
  const store=useAppStore();const child=store.selectedChild;const dimensions=useWindowDimensions();const insets=useSafeAreaInsets();
  const[lesson,setLesson]=useState<any>(bundledLesson);const[session,setSession]=useState<number>();const[idx,setIdx]=useState(0);const[runNumber,setRunNumber]=useState(1);
  const[stage,setStage]=useState<RuntimeStage>('ENTER');const[recording,setRecording]=useState(false);const[busy,setBusy]=useState(false);const[feedback,setFeedback]=useState('');
  const[choice,setChoice]=useState('');const[cardQuestionIndex,setCardQuestionIndex]=useState(0);const[packed,setPacked]=useState<string[]>([]);const[completed,setCompleted]=useState<any>();
  const[targetText,setTargetText]=useState('');const[nativeText,setNativeText]=useState('');const[interactiveState,setInteractiveState]=useState<Record<string,any>>({});const[recordedPhrases,setRecordedPhrases]=useState<string[]>([]);const[riddleRevealed,setRiddleRevealed]=useState(false);
  const[workingDifficulty,setWorkingDifficulty]=useState(Number(child?.workingDifficulty||0.15));const[languageLevel,setLanguageLevel]=useState(child?.languageLevel||'PRE_A1');const[visualSource,setVisualSource]=useState<any>();const[visualError,setVisualError]=useState('');
  const recorder=useAudioRecorder(RecordingPresets.HIGH_QUALITY);const recorderState=useAudioRecorderState(recorder,200);const voicePlayer=useAudioPlayer(null);const voiceStatus=useAudioPlayerStatus(voicePlayer);
  const heroAnim=useRef(new Animated.Value(0)).current;const stoppingRef=useRef(false);const afterSpeechRef=useRef<RuntimeStage>('NEXT');const wasSpeakingRef=useRef(false);const speechTokenRef=useRef(0);
  const allSlides:any[]=lesson?.slides||[];const runtimeOrder=useMemo(()=>buildRuntimeOrder(allSlides),[lesson]);const slide=runtimeOrder[idx];
  const targetLang=child?.learningLanguage||'ru';const nativeLang=child?.nativeLanguage||'ru';const layout=lessonLayoutPolicy(dimensions.width,dimensions.height,insets.bottom);
  const isSelector=slide?.interaction_kind==='card_question_sequence'||slide?.type==='card_selector';const isSuitcase=slide?.interactive_task==='suitcase';const isAnimalPair=slide?.type==='animal_compare';const isMood=slide?.type==='mood_choice';const isGift=slide?.interaction_kind==='gift_selector';const isGiraffe=slide?.slide_id==='slide_45';
  const selectedBranch=isSelector&&choice?selectedCardBranch(allSlides,choice):undefined;const artworkSlide=selectedBranch||slide;
  const activeCardQuestion=isSelector?cardQuestions(slide,choice)[cardQuestionIndex]:undefined;
  const voiceKey=isSelector&&activeCardQuestion?cardVoiceKey(slide.slide_id,choice,activeCardQuestion):String(slide?.required_phrase_id||slide?.slide_id||'');
  const hasSelection=isSuitcase?packed.length>0:isGiraffe?riddleRevealed:requiresSelection(slide)?Boolean(choice):true;
  const canRecord=recordEnabled(stage,slide,hasSelection)&&!busy&&!recording;
  const heroUri=child?.heroUrl?(child.heroUrl.startsWith('http')?child.heroUrl:API_BASE+child.heroUrl):undefined;const heroRect=heroBox(slide,lesson);

  useEffect(()=>{let active=true;(async()=>{if(!child)return;try{const current=await getLesson('demo_001');if(!active)return;setLesson(current);const order=buildRuntimeOrder(current.slides||[]);const response=await startSession(child.id,'demo_001');if(!active)return;setInteractiveState(response.interactive_state||{});setRecordedPhrases(response.recorded_phrases||[]);setWorkingDifficulty(Number(response.adaptive_profile?.working_difficulty||child.workingDifficulty||0.15));setLanguageLevel(response.adaptive_profile?.language_level||child.languageLevel||'PRE_A1');setSession(response.session_id);setRunNumber(response.run_number||1);setIdx(Math.min(Math.max(Number(response.current_step)||0,0),Math.max(order.length-1,0)))}catch(error:any){if(!active||isUnauthorizedError(error))return;Alert.alert('Урок недоступен',error.message);store.setScreen('home')}})();return()=>{active=false;speechTokenRef.current+=1}},[child?.id]);

  useEffect(()=>{if(voiceStatus.playing||voiceStatus.isBuffering){wasSpeakingRef.current=true;return}if(wasSpeakingRef.current&&stage==='AI_SPEAKING'){wasSpeakingRef.current=false;setStage(afterSpeechRef.current)}},[voiceStatus.playing,voiceStatus.isBuffering,stage]);

  useEffect(()=>{if(!artworkSlide?.image||!child)return;let active=true;setVisualError('');if(targetLang==='ru'){setVisualSource(mediaSource(artworkSlide));return()=>{active=false}};(async()=>{try{const source=await lessonVisualSource(lesson.lesson_id||'demo_001',artworkSlide.image,child.id,lesson.visual_asset_version||lesson.revision||1);if(active)setVisualSource(source)}catch(error:any){if(active){setVisualSource(undefined);setVisualError(error.message||'Иллюстрация пока недоступна')}}})();return()=>{active=false}},[artworkSlide?.image,targetLang,child?.id,lesson?.visual_asset_version]);

  useEffect(()=>{if(!slide||!session)return;let active=true;const stored=interactiveState[slide.slide_id]||{};const restoredChoice=String(stored.selected_card_id||stored.choice||stored.selected_animal||stored.selected_gift||stored.mood||'');const restoredPacked=Array.isArray(stored.selected)?stored.selected.map(String):[];const restoredIndex=Math.max(0,Number(stored.card_question_index)||0);const restoredRiddle=Boolean(stored.revealed);setChoice(restoredChoice);setPacked(restoredPacked);setCardQuestionIndex(restoredIndex);setRiddleRevealed(restoredRiddle);setFeedback('');setStage('ENTER');Animated.loop(Animated.sequence([Animated.timing(heroAnim,{toValue:1,duration:800,useNativeDriver:true}),Animated.timing(heroAnim,{toValue:0,duration:800,useNativeDriver:true})]),{iterations:2}).start();
    (async()=>{try{
      let sourcePrompt=runtimePrompt(slide,languageLevel,workingDifficulty,'initial');let finalStage=stageAfterTutorSpeech(slide,Boolean(restoredChoice));
      if(isSelector&&restoredChoice){const q=cardQuestions(slide,restoredChoice)[restoredIndex];if(q)sourcePrompt=runtimePrompt({bot_says_target:q.text,adaptive:true},languageLevel,workingDifficulty,'initial');if(stored.completed)finalStage='NEXT'}
      if(isGift&&restoredChoice)sourcePrompt=`Мила привезла мне ${selectedAnswerValueRu(slide,restoredChoice)}.`;
      if(isAnimalPair&&restoredChoice)sourcePrompt=VOICE_EXAMPLES_RU[String(slide.required_phrase_id||slide.slide_id)]||'Я вижу животное.';
      if((isGift||isAnimalPair)&&restoredChoice&&recordedPhrases.includes(String(slide.required_phrase_id||slide.slide_id)))finalStage='NEXT';
      if(isSuitcase){finalStage=restoredPacked.length?(recordedPhrases.includes(String(slide.required_phrase_id||slide.slide_id))?'NEXT':'WAITING_VOICE'):'WAITING_INTERACTION'}
      if(isMood)finalStage=restoredChoice?'NEXT':'WAITING_INTERACTION';if(isGiraffe)finalStage=restoredRiddle?(recordedPhrases.includes('giraffe')?'NEXT':'WAITING_VOICE'):'WAITING_INTERACTION';
      if(requiresVoice(slide)&&!isSelector&&!isSuitcase&&!isGift&&!isAnimalPair&&!isGiraffe&&recordedPhrases.includes(String(slide.required_phrase_id||slide.slide_id)))finalStage='NEXT';
      const[translatedTarget,translatedNative]=await Promise.all([translateText(sourcePrompt,targetLang,'ru'),translateText(String(slide.bot_explains_native||''),nativeLang,'ru')]);if(!active)return;setTargetText(translatedTarget||sourcePrompt);setNativeText(translatedNative||'');
      if(finalStage==='NEXT'&&(stored.completed||recordedPhrases.includes(String(slide.required_phrase_id||slide.slide_id))||restoredChoice&&isMood)){setStage('NEXT');return}
      await speakTarget(translatedTarget||sourcePrompt,targetLang,finalStage);
    }catch(error:any){if(active){setFeedback(`Не удалось подготовить голос ведущей: ${error.message||error}`);setStage(stageAfterTutorSpeech(slide,hasSelection))}}})();return()=>{active=false;speechTokenRef.current+=1}},[idx,session,targetLang,nativeLang]);

  useEffect(()=>{const limit=Math.max(1,Number(slide?.max_voice_seconds||5))*1000;if(recording&&recorderState.durationMillis>=limit&&!stoppingRef.current)void stopRec()},[recording,recorderState.durationMillis,slide?.slide_id]);

  async function speakTarget(text:string,sourceLanguage=targetLang,after:RuntimeStage=stageAfterTutorSpeech(slide,hasSelection)){
    if(!text){setStage(after);return}const token=++speechTokenRef.current;afterSpeechRef.current=after;wasSpeakingRef.current=false;setStage('AI_SPEAKING');
    try{const source=await ttsSource(text,targetLang,'',nativeLang,sourceLanguage);if(token!==speechTokenRef.current)return;voicePlayer.replace(source);voicePlayer.play()}
    catch(error:any){if(token===speechTokenRef.current){setFeedback('Голос ведущей временно недоступен. Можно продолжить задание по тексту.');setStage(after)}}
  }

  async function persistInteraction(result:any){if(!session||!slide)return;setInteractiveState(current=>({...current,[slide.slide_id]:result}));await sendInteractive(session,slide.slide_id,slide.interactive_task||slide.type||'choice',result)}

  async function chooseArtwork(value:string){if(stage!=='WAITING_INTERACTION'||busy)return;Vibration.vibrate(12);setChoice(value);setFeedback('');try{
    if(isSelector){const questions=cardQuestions(slide,value);const first=questions[0];if(!first)throw new Error('У выбранной карточки нет вопросов');setCardQuestionIndex(0);await persistInteraction({selected_card_id:value,card_question_index:0,completed:false,question_ids:questions.map(item=>item.id)});const source=runtimePrompt({bot_says_target:first.text,adaptive:true},languageLevel,workingDifficulty,'initial');const translated=await translateText(source,targetLang,'ru');setTargetText(translated||source);setFeedback(`Карточка ${value} выбрана.`);await speakTarget(translated||source,targetLang,'WAITING_VOICE');return}
    if(isAnimalPair){await persistInteraction({selected_animal:value,pair_id:slide.pair_id});const source=VOICE_EXAMPLES_RU[String(slide.required_phrase_id||slide.slide_id)]||'Я вижу животное.';const translated=await translateText(source,targetLang,'ru');setTargetText(translated||source);setFeedback('Животное выбрано. Дослушай ведущую и ответь.');await speakTarget(translated||source,targetLang,'WAITING_VOICE');return}
    if(isGift){await persistInteraction({selected_gift:value});const source=`Мила привезла мне ${selectedAnswerValueRu(slide,value)}.`;const translated=await translateText(source,targetLang,'ru');setTargetText(translated||source);setFeedback('Подарок выбран. Дослушай ведущую и назови его голосом.');await speakTarget(translated||source,targetLang,'WAITING_VOICE')}
  }catch(error:any){setFeedback('Не удалось сохранить выбор: '+error.message);setStage('WAITING_INTERACTION')}}

  async function chooseGiraffe(value:string){if(stage!=='WAITING_INTERACTION'||busy)return;Vibration.vibrate(12);if(value!=='giraffe'){setFeedback('Попробуй другой рисунок.');await speakTarget(targetText,targetLang,'WAITING_INTERACTION');return}setChoice(value);setRiddleRevealed(true);await persistInteraction({choice:value,revealed:true});const source='Это жираф. У него длинная шея и пятна.';const translated=await translateText(source,targetLang,'ru');setTargetText(translated||source);setFeedback('Верно. Теперь назови один-два признака.');await speakTarget(translated||source,targetLang,'WAITING_VOICE')}
  async function toggleSuitcase(itemId:string){if(!['WAITING_INTERACTION','WAITING_VOICE'].includes(stage)||busy)return;Vibration.vibrate(8);const selected=packed.includes(itemId)?packed.filter(id=>id!==itemId):[...packed,itemId];setPacked(selected);await persistInteraction({selected,useful_selected:selected.filter(id=>SUITCASE_ITEMS.some(item=>item.id===id&&item.useful)),completed:false});setStage(selected.length?'WAITING_VOICE':'WAITING_INTERACTION')}
  async function chooseMood(index:number){if(stage!=='WAITING_INTERACTION'||busy)return;Vibration.vibrate(8);const mood=String(slide.mood_options?.[index]||`mood_${index}`);setChoice(mood);await persistInteraction({mood,index,emoji:MOOD_EMOJIS[index],completed:true});const spoken=await translateText(mood,targetLang,'ru');setTargetText(spoken);setFeedback('Настроение выбрано ✓');await speakTarget(spoken,targetLang,'NEXT')}

  async function startRec(){if(!session||!canRecord)return;try{stoppingRef.current=false;const permission=await requestRecordingPermissionsAsync();if(!permission.granted){Alert.alert('Нужен доступ к микрофону');return}await setAudioModeAsync({allowsRecording:true,playsInSilentMode:true});await recorder.prepareToRecordAsync();recorder.record();setRecording(true);setFeedback('Говори — я тебя слушаю. Когда закончишь, нажми ещё раз.')}catch(error:any){Alert.alert('Микрофон',error.message)}}

  async function stopRec(){if(!recording||!session||busy||stoppingRef.current)return;stoppingRef.current=true;try{setBusy(true);setStage('PROCESSING');setFeedback('Слушаю и проверяю ответ…');await recorder.stop();setRecording(false);const uri=recorder.uri;if(!uri)throw new Error('Файл записи не создан');const response=await sendVoice(session,uri,slide.slide_id,voiceKey,targetText||slide.question||slide.bot_says_target||'');const profile=response.adaptive_profile||{};const nextDifficulty=profile.working_difficulty!==undefined?Number(profile.working_difficulty):workingDifficulty;const nextLevel=profile.language_level?String(profile.language_level):languageLevel;setWorkingDifficulty(nextDifficulty);setLanguageLevel(nextLevel);
      const accepted=Boolean(response.accepted);if(accepted)setRecordedPhrases(items=>items.includes(voiceKey)?items:[...items,voiceKey]);const heard=response.transcript?`Я услышала: «${response.transcript}». `:'';setFeedback(heard+(response.feedback||response.response_native||(accepted?'Хорошо, идём дальше.':'Попробуй ещё раз.')));const result=advanceAfterAssessment(response);
      if(result==='COMPLETE'&&isSelector){const nextQuestion=nextCardQuestion(slide,choice,cardQuestionIndex);if(!nextQuestion.done&&nextQuestion.question){setStage('FEEDBACK');setCardQuestionIndex(nextQuestion.index);await persistInteraction({selected_card_id:choice,card_question_index:nextQuestion.index,completed:false,question_ids:cardQuestions(slide,choice).map(item=>item.id)});const questionSource=runtimePrompt({bot_says_target:nextQuestion.question.text,adaptive:true},nextLevel,nextDifficulty,'initial');const translated=await translateText(questionSource,targetLang,'ru');setTargetText(translated||questionSource);let lead=String(response.response_target||'').trim();if(!lead&&response.feedback)lead=await translateText(String(response.feedback),targetLang,String(response.feedback_source_language||'ru'));await speakTarget([lead,translated||questionSource].filter(Boolean).join(' '),targetLang,'WAITING_VOICE');return}await persistInteraction({selected_card_id:choice,card_question_index:cardQuestions(slide,choice).length,completed:true,question_ids:cardQuestions(slide,choice).map(item=>item.id)});setStage('FEEDBACK');const speech=String(response.response_target||response.feedback||'').trim();if(speech)await speakTarget(speech,response.response_target?targetLang:String(response.feedback_source_language||nativeLang),'NEXT');else setStage('NEXT');return}
      const after:RuntimeStage=result==='COMPLETE'?'NEXT':'WAITING_VOICE';setStage(result==='COMPLETE'?'FEEDBACK':'RETRY_OR_COMPLETE');let speech='';let sourceLanguage=targetLang;if(result==='RETRY'){speech=String(response.correction_target||response.feedback||'');sourceLanguage=String(response.correction_target?response.correction_source_language:response.feedback_source_language||'ru')}else{speech=String(response.response_target||response.feedback||'');sourceLanguage=String(response.response_target?targetLang:response.feedback_source_language||nativeLang)}if(speech){const translated=sourceLanguage===targetLang?speech:await translateText(speech,targetLang,sourceLanguage);await speakTarget(translated||speech,targetLang,after)}else setStage(after)
    }catch(error:any){console.error('stopRec error',error);setRecording(false);setStage('WAITING_VOICE');setFeedback('Запись не засчитана: '+error.message)}finally{try{await setAudioModeAsync({allowsRecording:false,playsInSilentMode:true})}catch{}stoppingRef.current=false;setBusy(false)}}

  const next=async()=>{if(!nextEnabled(stage)||busy)return;if(idx<runtimeOrder.length-1){try{setBusy(true);setStage('ENTER');if(session)await saveSessionProgress(session,idx+1);setIdx(value=>value+1)}catch(error:any){Alert.alert('Не удалось сохранить урок',error.message);setStage('NEXT')}finally{setBusy(false)}return}if(!session)return;try{setBusy(true);setCompleted(await completeSession(session))}catch(error:any){Alert.alert('Не удалось завершить урок',error.message)}finally{setBusy(false)}};
  const exitLesson=async()=>{try{if(session)await saveSessionProgress(session,idx)}catch(error:any){Alert.alert('Не удалось сохранить урок',error.message);return}store.setScreen('home')};

  if(completed)return <ScrollView contentContainerStyle={{padding:24,paddingBottom:24+insets.bottom}}><H1>Урок завершён 🎉</H1><Card><H2>Прохождение {completed.run_number||runNumber}</H2>{completed.movie_status==='READY'?<Body>🎬 Персональный мультфильм M‑1 готов.</Body>:<Body muted>🎬 Мультфильм: {completed.movie_status==='PROCESSING'?'обрабатывается на сервере':completed.movie_status==='MISSING_VOICE'?'нужны все реплики урока':'пока недоступен'}.</Body>}{completed.movie_url?<Button title='▶ Посмотреть мультфильм' onPress={()=>Linking.openURL(completed.movie_url)}/>:null}</Card><Button title='Вернуться домой' onPress={()=>store.setScreen('home')}/></ScrollView>;
  if(!slide)return <View style={{padding:24}}><Body>Загрузка урока…</Body></View>;

  let artworkOptions:SelectableImageOption[]=[];if(isSelector&&!choice)artworkOptions=configuredOptions(slide,CARD_OPTIONS);else if(isGift)artworkOptions=configuredOptions(slide);else if(isAnimalPair)artworkOptions=ANIMAL_PAIR_OPTIONS[slide.pair_id]||[];const showArtwork=Boolean(artworkSlide?.image)&&!isSuitcase&&!isMood&&(!isGiraffe||riddleRevealed);
  const controls=<View style={{flex:layout.landscape?layout.controlFlex:undefined,minWidth:layout.landscape?300:undefined}}><Card compact={layout.compact}><ScrollView style={{maxHeight:layout.compact?95:150}} nestedScrollEnabled>{targetText?<><Body compact={layout.compact} muted>Ведущая говорит ({targetLang})</Body><H2 compact={layout.compact}>{targetText}</H2></>:null}{nativeText&&nativeLang!==targetLang?<><Body compact={layout.compact} muted>Подсказка ({nativeLang})</Body><Body compact={layout.compact}>{nativeText}</Body></>:null}{feedback?<Body compact={layout.compact}>{feedback}</Body>:null}</ScrollView><Body compact={layout.compact} muted>Этап: {stage} · сложность {Math.round(workingDifficulty*100)}%</Body><Button compact={layout.compact} secondary disabled={stage==='AI_SPEAKING'||recording||busy} title={stage==='AI_SPEAKING'?'🔊 Ведущая говорит…':'🔊 Повторить'} onPress={()=>speakTarget(targetText,targetLang,stage)}/>{requiresVoice(slide)?<Button compact={layout.compact} testID='record-answer' disabled={!canRecord&&!recording} title={stage==='AI_SPEAKING'?'🔊 Сначала дослушай':recording?'⏹ Закончить запись':stage==='PROCESSING'?'Проверяю ответ…':'🎙 Записать ответ'} onPress={recording?stopRec:startRec}/>:null}</Card><Button compact={layout.compact} disabled={!nextEnabled(stage)||busy} title={idx<runtimeOrder.length-1?'Дальше →':'Завершить урок'} onPress={next}/><View style={{flexDirection:'row',gap:6}}><View style={{flex:1}}><Button compact secondary title='🌍 Языки' onPress={()=>store.setScreen('language')}/></View><View style={{flex:1}}><Button compact secondary title='Выйти и сохранить' onPress={exitLesson}/></View></View></View>;

  return <View testID={`runtime-stage-${stage}`} style={{flex:1,padding:layout.contentPadding,paddingBottom:layout.bottomPadding}}><View><H1 compact={layout.compact}>DOME · {targetLang.toUpperCase()}</H1><Body compact={layout.compact} muted>{idx+1}/{runtimeOrder.length} · прохождение {runNumber} · уровень {languageLevel}</Body></View><View style={{flex:1,flexDirection:layout.landscape?'row':'column',gap:layout.contentPadding}}><ScrollView style={{flex:layout.visualFlex}} contentContainerStyle={{paddingBottom:6}}>
    {visualError?<Card compact><Body compact>Иллюстрация для языка {targetLang.toUpperCase()} ещё готовится. Русский оригинал не показывается.</Body></Card>:null}
    {showArtwork&&visualSource?<SelectableArtwork slide={slide} source={visualSource} heroUri={heroUri} heroRect={heroRect} heroAnim={heroAnim} options={artworkOptions} selected={choice} onSelect={chooseArtwork} onImageError={()=>setVisualError('Не удалось загрузить локализованную иллюстрацию')}/>:null}
    {isSelector&&choice&&activeCardQuestion?<Card compact={layout.compact}><H2 compact={layout.compact}>Карточка {choice} · вопрос {cardQuestionIndex+1}/{cardQuestions(slide,choice).length}</H2><Body compact={layout.compact}>{targetText}</Body></Card>:null}
    {isGiraffe&&!riddleRevealed?<Card compact={layout.compact}><H2 compact={layout.compact}>Угадай по голосу</H2><View style={{flexDirection:'row',justifyContent:'space-around'}}>{GIRAFFE_CHOICES.map(item=><Pressable testID={`giraffe-choice-${item.id}`} accessibilityRole='button' accessibilityLabel={item.label} key={item.id} onPress={()=>chooseGiraffe(item.id)} style={{minWidth:72,minHeight:72,borderRadius:18,borderWidth:3,borderColor:choice===item.id?'#13a864':'#d9dee6',alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:42}}>{item.emoji}</Text></Pressable>)}</View></Card>:null}
    {isSuitcase?<Card compact={layout.compact}><H2 compact={layout.compact}>🧳 Чемодан</H2><Body compact={layout.compact}>Нажми на вещь, чтобы положить её в чемодан.</Body><View testID='suitcase-drop-zone' style={{minHeight:82,borderWidth:3,borderStyle:'dashed',borderColor:'#6aa6d8',borderRadius:18,padding:6,flexDirection:'row',flexWrap:'wrap',gap:5}}>{packed.length?packed.map(id=><Pressable key={`packed-${id}`} onPress={()=>toggleSuitcase(id)}><Image source={suitcaseImages[id]} style={{width:58,height:58,resizeMode:'contain'}}/></Pressable>):<Body compact muted>Здесь появятся выбранные вещи</Body>}</View><View style={{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:8}}>{SUITCASE_ITEMS.filter(item=>!packed.includes(item.id)).map(item=><Pressable testID={`suitcase-item-${item.id}`} accessibilityRole='button' accessibilityLabel={item.label} key={item.id} onPress={()=>toggleSuitcase(item.id)} style={{width:'22%',minHeight:70,borderWidth:1,borderColor:'#ddd',borderRadius:12,alignItems:'center',justifyContent:'center'}}><Image source={suitcaseImages[item.id]} style={{width:54,height:54,resizeMode:'contain'}}/></Pressable>)}</View></Card>:null}
    {isMood?<Card compact={layout.compact}><H2 compact={layout.compact}>Какое у тебя настроение?</H2><View style={{flexDirection:'row',flexWrap:'wrap',gap:8,justifyContent:'center'}}>{MOOD_EMOJIS.map((emoji,index)=><Pressable testID={`mood-${index}`} accessibilityRole='button' accessibilityLabel={`Mood ${index+1}`} key={index} onPress={()=>chooseMood(index)} style={{width:70,height:70,borderRadius:18,borderWidth:4,borderColor:choice===slide.mood_options?.[index]?'#13a864':'#d9dee6',alignItems:'center',justifyContent:'center',backgroundColor:'#fff'}}><Text style={{fontSize:44}}>{emoji}</Text></Pressable>)}</View></Card>:null}
  </ScrollView>{controls}</View></View>;
}
