-- Logical production schema (adapt to PostgreSQL migrations)
create table parents(id uuid primary key, name text not null, country text, phone_e164 text, phone_verified_at timestamptz, email text, email_verified_at timestamptz, ui_language text not null, created_at timestamptz not null default now());
create table children(id uuid primary key, parent_id uuid not null references parents(id), name text not null, birth_date date, learning_language text not null, created_at timestamptz not null default now());
create table consent_documents(id uuid primary key, consent_type text not null, version text not null, language text not null, body text not null, sha256 text not null, effective_at timestamptz not null, unique(consent_type,version,language));
create table consent_acceptances(id uuid primary key, parent_id uuid not null references parents(id), child_id uuid references children(id), document_id uuid not null references consent_documents(id), accepted_at timestamptz not null, session_id text not null, app_version text not null, verification_snapshot jsonb not null, evidence jsonb not null);
create table orders(id uuid primary key, parent_id uuid not null references parents(id), child_id uuid references children(id), plan_id text not null, lessons integer not null, access_months integer not null, amount_cents integer not null, currency text not null, recurring boolean not null, status text not null, provider text, provider_transaction_id text, created_at timestamptz not null default now());
create table entitlements(id uuid primary key, child_id uuid not null references children(id), course_id text not null, lesson_id text not null, order_id uuid references orders(id), unlocked_at timestamptz not null, expires_at timestamptz not null, max_completions integer not null default 2, completions integer not null default 0, status text not null);
create table lesson_sessions(id uuid primary key, entitlement_id uuid not null references entitlements(id), attempt integer not null check(attempt in(1,2)), current_scene_id text, status text not null, started_at timestamptz not null, completed_at timestamptz);
create table voice_records(id uuid primary key, session_id uuid not null references lesson_sessions(id), scene_id text not null, object_key text, transcript text, retention_until timestamptz, deleted_at timestamptz, created_at timestamptz not null default now());
create table movies(id uuid primary key, session_id uuid not null unique references lesson_sessions(id), attempt integer not null, object_key text, status text not null, parent_emailed_at timestamptz, created_at timestamptz not null default now());
create table homework(id uuid primary key, entitlement_id uuid not null unique references entitlements(id), issued_from_attempt integer not null default 1, payload jsonb not null, child_delivered_at timestamptz, parent_emailed_at timestamptz, created_at timestamptz not null default now());
create table evidence_events(id uuid primary key, parent_id uuid not null references parents(id), child_id uuid references children(id), event_type text not null, event_key text not null unique, occurred_at timestamptz not null, payload jsonb not null);
